{% set name = "solo-epd-loader" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solo_epd_loader-{{ version }}.tar.gz
  sha256: 553f97e4b80f4ff111f987b843431409ca271d9e67cab6aece0abc55cb466c61

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - cdflib
    - h5netcdf
    - heliopy
    - numpy
    - pandas
    - python >=3.6
    - requests
    - sunpy

test:
  imports:
    - solo_epd_loader
    - solo_epd_loader.tests
  requires:
    - pip

about:
  home: https://github.com/jgieseler/solo-epd-loader
  summary: Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  license: BSD-3-Clause
  license_file:
    - licenses/LICENSE.rst
    - licenses/TEMPLATE_LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
